### ISSUE TITLE
请问如何播放m3u地址？

### ISSUE THREAD

**Issue by twedu** [tsl0922/ImPlay#1]
订阅的那种在线播放地址，vlc直接可以打开添加。没有找到入口。

**Comment by tsl0922** [comment]
这种还没有做界面支持，暂时可以先命令行传 url，或者创建个快捷方式，把url 放到快捷方式的参数里，双击就可以自动打开了

**Comment by twedu** [comment]
我平时偶尔会在电脑上测试下蓝光原盘的导航菜单，这个后续会支持么？

**Comment by tsl0922** [comment]
已经支持从剪贴板打开 URL 或者文件路径。另外，也添加了打开蓝光文件夹的支持。Releases 下的 windows 二进制文件已更新。

**Comment by tsl0922** [comment]
mpv 是不支持导航菜单的，所以短期内可能不会做。

**Comment by twedu** [comment]
太棒了，在我的电脑里它已经替代了vlc，thx~

Shuanglei Tao ***@***.***> 于2023年1月1日周日 12:35写道：
