### ISSUE TITLE
Space button to play last video when on idle screen

### ISSUE THREAD

**Issue by rollingmoai** [tsl0922/ImPlay#11]
**Is your feature request related to a problem? Please describe.**
This is my favorite feature from mpv.net, please add!

**Describe the solution you'd like**
Space button to play last video when on idle screen

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by candrapersada** [comment]
and add bookmark too

**Comment by tsl0922** [comment]
Implemented it with a `play-pause`  command like mpv.net.

To use it, check `Help - Settings - Space to play last file on IDLE*` and restart ImPlay, or add the following line to your `input.conf`:

```
Space script-message-to implay play-pause
```
