### ISSUE TITLE
Instructions for building?

### ISSUE THREAD

**Issue by Impeta** [tsl0922/ImPlay#12]
Sorry, but I can't seems to grasp how do you really build your project from source. Is this really for Ubuntu only? I'm on EndeavorOS, Arch-based if that matters. Any directions, please? Thanks in advance!

**Comment by tsl0922** [comment]
It should work on all linux distributions. Does the AppImage package work for you?

**Comment by candrapersada** [comment]
or flatpak

**Comment by tsl0922** [comment]
@Impeta  I've add a compiling document: https://github.com/tsl0922/ImPlay/blob/main/docs/compiling.md

The windows build is pacman based, maybe youcan refer to it.

PRs to add instructions for other system / distribution are welcomed.

**Comment by tsl0922** [comment]
Closing as it's answered.
