### ISSUE TITLE
How to add GLSL shaders?

### ISSUE THREAD

**Issue by ramonsantana** [tsl0922/ImPlay#13]
How do i add Anime4k shaders to this program and how to add the keyboard shortcuts for it?

**Comment by tsl0922** [comment]
put your mpv config into `Tools-Open Config Dir`, or `Help-Settings-Use mpv's config dir`.

Also: https://github.com/tsl0922/ImPlay/wiki/FAQ

**Comment by tsl0922** [comment]
I'm closing this issue, feel free to reopen if you still have any question.
