### ISSUE TITLE
AppImage requires libOpenGL.so.0 to run.

### ISSUE THREAD

**Issue by re0man** [tsl0922/ImPlay#14]
The AppImage requires `libOpenGL.so.0`. Although the problem can be solved by running `sudo apt install libopengl0`, but i was thinking that if it was possible to make it in a way so that the `libOpenGL.so.0` library isn't required anymore, then the AppImage would be totally self-contained.

*Sorry if this doesn't make any sense, English isn't my first language.*

**Comment by tsl0922** [comment]
It's not supported in the build tool we used.

https://github.com/linuxdeploy/linuxdeploy/issues/5
