### ISSUE TITLE
libmpv renderer backend

### ISSUE THREAD

**Issue by tsl0922** [tsl0922/ImPlay#15]
libmpv provides OpenGL renderer API only, but it does not perform best on all platforms:

- OpenGL is slower than D3D11 on Windows
- Apple deprecates OpenGL on macOS
- Does not support `gpu-next` yet: https://github.com/mpv-player/mpv/issues/10810

Upstream feature requests: [D3D11](https://github.com/mpv-player/mpv/issues/5979), [Vulkan](https://github.com/mpv-player/mpv/issues/6575)

Luckily, we can use translation layer like [ANGLE](https://github.com/google/angle), which may translate OpenGL ES API calls to a faster hardware-supported APIs to improve performance. Also, ANGLE makes ImPlay work on Virtual Machines that doesn't have a OpenGL 3 driver (example: HyperV vm has D3D driver only). The downside is, it may break HDR: https://github.com/mpv-player/mpv/issues/8530

I've implemented OpenGL ES 2.0 support on the latest main branch, and it's now built in actions (tested the windows version).

> **NOTE:** EGL and GLESv2 dynamic libraries is required to run the GLES2 version of ImPlay, but not needed at build time.

**Comment by dragonflylee** [comment]
here is my implement of d3d11 api for mpv 
https://github.com/dragonflylee/mingw-packages/blob/dev/mpv/0001-d3d11-render.patch

and example https://gist.github.com/dragonflylee/5b73c0df5db85dba03488d592f1af23a

**Comment by tsl0922** [comment]
Thanks. I don't want to use a patched mpv, and [ANGLE](https://github.com/google/angle) works fine.

**Comment by dragonflylee** [comment]
But hwaccel didn't work correctly on my Yoga730 (i5-8250u UHD620), and fallback to `dxva2-copy`,
Test log below

```
ImPlay.com --terminal=yes --gpu-context=angle "D:\[Sakurato] Spy x Family S2 - 01.mkv"
[libmpv_render/dxva2-egl] Failed to create EGL surface
Cannot load nvcuda.dll
 (+) Video --vid=1 (*) (hevc 1920x1080 23.976fps)
 (+) Audio --aid=1 --alang=jpn (*) 'Audio' (aac 2ch 44100Hz)
 (+) Subs  --sid=1 --slang=chi (*) '[桜都字幕组] Simplified Chinese' (ass)
     Subs  --sid=2 --slang=chi '[桜都字幕组] Traditional Chinese' (ass)
File tags:
 Comment: Auto Video Processor 3.0.04 @Sakurato
Using hardware decoding (dxva2-copy).
AO: [wasapi] 48000Hz stereo 2ch float
VO: [libmpv] 1920x1080 p010
[libmpv_render] after creating texture: OpenGL error INVALID_FRAMEBUFFER_OPERATION.
Option af-remove: item label @aeq not found.
```

**Comment by tsl0922** [comment]
You don't need to specify gpu-context, it should select `d3d11va-copy` automatically.

**Comment by tsl0922** [comment]
Currently, both the video and gui are rendering with OpenGL. To adding another backend for mpv, we need to add it for imgui too. It means a lot of work to me, so I'm also considering to use the window embeding feature of mpv (`--wid`).
