### ISSUE TITLE
Cannot add external subtitles by dragging and dropping

### ISSUE THREAD

**Issue by Tohhanabi** [tsl0922/ImPlay#16]
**Describe the bug**
When dragging in subtitles to a video being played, ImPlay treats the subtitle file as a new video and then tries to play it, with the apparent result that it does not play.

**Expected behavior**
A subtitle track has been added to the video.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version 22H2
 - ImPlay 1.1.1

**Comment by tsl0922** [comment]
Implemented on main, you can try it with the dev build:

https://github.com/tsl0922/ImPlay/releases/tag/continuous

**Comment by Tohhanabi** [comment]
> Implemented on main, you can try it with the dev build:
> 
> https://github.com/tsl0922/ImPlay/releases/tag/continuous

The problem has been solved, thank you.
