### ISSUE TITLE
[Question] GLFW Wayland Support

### ISSUE THREAD

**Issue by 135e2** [tsl0922/ImPlay#17]
After [`9a09f57`](https://github.com/tsl0922/ImPlay/commit/9a09f57181c82338872594fa4a5de27352c94c65), self-compiled ImPlay started to throw Wayland error spams like this:

> `GLFW [65544]: Wayland: Window position retrieval not supported`

A quick searchthrough led me here:
https://github.com/WerWolv/ImHex/issues/30

It seems that you changed USE_PATCHED_GLFW and started to use upstream library directly, thus leading this issue. I'm not a cpp expert, but may that be somehow related to differences between your upstream and your patched version of GLFW?

---
Update:
Manually enabling patched GLFW with `-DUSE_PATCHED_GLFW=ON` seems fine.

OS: Archlinux, Plasma(Wayland)

**Comment by tsl0922** [comment]
`-DUSE_PATCHED_GLFW=ON` won't compile glfw with wayland support, so you're not using wayland anymore.

Didn't test wayland before, but it should work on it. The error spams is triggered by imgui's glfw backend. 

According to https://github.com/WerWolv/ImHex/issues/30#issuecomment-739333794 by @ocornut, I've added an option to allow disabling multi-viewports support.
<img width="341" alt="image" src="https://user-images.githubusercontent.com/1680515/216886751-017a4f60-8cf7-45ed-b58c-6c36402a4ea3.png">
