### ISSUE TITLE
ImPlay-win64.msi auto set environment variable PATH aftar install

### ISSUE THREAD

**Issue by candrapersada** [tsl0922/ImPlay#18]
does the `ImPlay-win64.msi` package support auto set environment variable PATH for command line?

**Comment by tsl0922** [comment]
It will register itself under `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths`.

https://learn.microsoft.com/en-us/windows/win32/shell/app-registration#using-the-app-paths-subkey

**Comment by candrapersada** [comment]
![gambar](https://user-images.githubusercontent.com/36833664/216816438-a85329d2-1898-45eb-b5f1-04d02882bc5f.png)

**Comment by tsl0922** [comment]
> The entries found under App Paths are used primarily for the following purposes:
>
> - To map an application's executable file name to that file's fully qualified path.
> - To pre-pend information to the PATH environment variable on a **per-application, per-process** basis.

Please read the ms document, the user or system PATH won't be modified, but you can run `ImPlay` from `Win+R` prompt.

**Comment by tsl0922** [comment]
so, the answer to your question is no.
