### ISSUE TITLE
why are there two monitors?

### ISSUE THREAD

**Issue by candrapersada** [tsl0922/ImPlay#2]
![gambar](https://user-images.githubusercontent.com/36833664/210533814-b8194b5f-20f0-4302-96fa-71cf03f5315f.png)

**Comment by tsl0922** [comment]
Which OS?

**Comment by candrapersada** [comment]
windows 10

**Comment by tsl0922** [comment]
Similar issue: https://github.com/mpv-player/mpv/issues/10189

I have no idea if this is a libmpv or implay issue, still trying to dig out it.

**Comment by tsl0922** [comment]
try the latest build, upgrading libmpv seems to fix it.

https://github.com/tsl0922/ImPlay/commit/a28fc38949e8a0e347e9ab68939d048de8df8e85

**Comment by tsl0922** [comment]
Fixed on the latest main.

**Comment by candrapersada** [comment]
why are there two monitors in
https://github.com/tsl0922/ImPlay/wiki/FAQ#how-to-turn-off-implay-logo

**Comment by tsl0922** [comment]
I have no idea, maybe it's mpv's bug, so ImPlay is not using `force-window` by default.

**Comment by Dreista** [comment]
Seems to be related to `--vo=` option. Setting `vo` to `gpu` or `gpu-next` would create a detached window.

Environment:
- OS: `Windows 11 Enterprise 22H2`
- OS build: `22621.1344`
- ImPlay version: `1.4.0`

Step to reproduce:
- Put `vo=gpu-next` into `mpv.conf`

**Comment by tsl0922** [comment]
ImPlay uses libmpv renderer API,  which does not support `gpu-next` yet (https://github.com/mpv-player/mpv/issues/10810).

**Comment by ToxicSmurf** [comment]
Consider putting that in the FAQ, pretty common setting.
