### ISSUE TITLE
Choose video and audio quality

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#20]
Hello, thank you very much for this amazing awesome palyer ! 💯 🥇 

Please I have request: videos in youtube and dailymotion and facebbok watch have many quality resolutions, and sometimes our notebook is weak and its graphics card weak or there are many spots, so it will be great to add button in the main interace to choose the video quality worst 144p, or standard video 360p or HD video 720p or 4K...and also choose to playback only the audio streams contained in the youtube video dash in order to save battery and the screen will be off when we sleep while we listen podcast in youtube and it's also useful when listening to the video in the background...thanks a lot !

**Comment by tsl0922** [comment]
Isn't it possible to be implemented with a lua script?

**Comment by trimechee** [comment]
I don't konw, and even i don't know how to use lua scripts... to make things easier, it will be great to add an option in the gui concerning yt-dlp where we can choose the audio or video formats that we want to use because sometime network ou notebook is very weak and can't play ultra HD video resolUtion smoothly !  Thank you very much :)

**Comment by tsl0922** [comment]
https://github.com/jgreco/mpv-youtube-quality

**Comment by trimechee** [comment]
Great ! Thank you very much ! 🥇 it says : "This conflicts with other scripts that modify the OSC", i fear if i modify something, it will crash our beloved ImPlay, may be it will be better to avoid bugs that such script is tested by ImPlay and integrated natively...

**Comment by trimechee** [comment]
Also it will be awesome to incorporate this important feature in ImPlay , thank you !

https://github.com/jonniek/mpv-playlistmanager

**Comment by tsl0922** [comment]
ImPlay already has a playlist manager in Context Menu - Quick Settings.

**Comment by trimechee** [comment]
Awesome !! 💯 🥇
