### ISSUE TITLE
ImPlay portable mode

### ISSUE THREAD

**Issue by firezt** [tsl0922/ImPlay#21]
Hello.
On Windows, is there any way to make ImPlay detect the `implay.conf` in a directory other than "%APPDATA%\implay"?
Like mpv does with the "portable_config" folder next to mpv.exe, for example. If not, is there a possibility to implement something like this? :smiley:

Thanks for reading.

**Comment by tsl0922** [comment]
Settings-Core-Use mpv's config dir

**Comment by firezt** [comment]
Yeah, I already did it. But I refer to the settings of ImPlay itself (implay.conf), not the libmpv ones.

**Comment by tsl0922** [comment]
Oops, it's hardcoded.

**Comment by firezt** [comment]
Got it.
Well, is there any chance of this being implemented? Maybe you can do like mpv, check if the folder exists in the root directory where ImPlay.exe is and use it, otherwise use the default in "%APPDATA%\implay".

**Comment by tsl0922** [comment]
The `portable_config` folder is now supported on windows on the latest main branch.

You can try it with the dev build: https://github.com/tsl0922/ImPlay/releases/tag/continuous

**Comment by tsl0922** [comment]
I've added a wiki page for it: https://github.com/tsl0922/ImPlay/wiki/Portable-Mode

**Comment by firezt** [comment]
Just tested it and it's working very well. Thanks a lot!
