### ISSUE TITLE
Autofit not working

### ISSUE THREAD

**Issue by Miracutor** [tsl0922/ImPlay#22]
**Describe the bug**
I specified autofit in my config but it was not reflected on the player. When opening the player, the player size same as the default. It is supposed to already be changed here like mpv. When loading a video, it also behaved the same. It ignored autofit-larger.

**To Reproduce**
1. Add these lines to mpv.conf.
```
autofit-larger=75% # Set max window size.  height/width
autofit-smaller=858x480 # Set min window size.
```
2. Open the player. See the size not changing.
3. Load any video. See video size not changing automatically.

**Expected behavior**
The player follows autofit-larger and autofit-smaller like mpv. That means when loading video, the player has to be at least larger than 848x480 and cannot exceed the window width 75% of the screen size while keeping the aspect ratio.

**Screenshots**
![image](https://user-images.githubusercontent.com/46325590/217227595-3bc82aa3-bda0-41de-9da7-17c250a5746e.png)
![image](https://user-images.githubusercontent.com/46325590/217227926-49e8b882-bdec-459f-876b-2e55de0b28f7.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Home
 - Version: 22H2

**Comment by tsl0922** [comment]
mpv's window related options need to be implemented on ImPlay window again, so not all of the options are supported now.

**Comment by tsl0922** [comment]
Closing as it's tracked in #27 now.
