### ISSUE TITLE
Ability to use custom keyboard shortcuts

### ISSUE THREAD

**Issue by re0man** [tsl0922/ImPlay#25]
Some options don't have keyboard shortcuts, like `Open Url` (which i use a lot). so i was thinking that if it was possible to let users add their custom keyboard shortcuts for different options. (Would it be possible to add URL playlist, like having `Add Url` Option into the playlist)

Also one thing to note: some times the ctrl+v doesn't work when pasting the url (on the `Input Url Here` prompt) it gets stuck and you can't even close the player.

The AppImage now works well, you don't need to download the `libOpenGL.so.0` library separately, thanks for that.

**Comment by tsl0922** [comment]
use: `script-message-to implay open-url`

https://github.com/tsl0922/ImPlay/wiki/Scripting-Interface
