### ISSUE TITLE
Huge menu for Mac OS

### ISSUE THREAD

**Issue by hooke007** [tsl0922/ImPlay#26]
**Describe the bug**
 The context menu of Mac ver. is much huge.

**To Reproduce**

 Run Implay and open the menu.

**Expected behavior**
 The reasonable rendering size。

**Screenshots**
 
<img width="1175" alt="截屏2023-02-10 14 30 25" src="https://user-images.githubusercontent.com/41094733/218118007-a6273338-205f-4496-8fbe-43904a3973fd.png">

**Environment (please complete the following information):**
 - OS: [Mac]
 - Version [13.2]

**Additional context**
 N/A

**Comment by tsl0922** [comment]
It's a known issue, change the scale to 1.x (Help - Settings - Interface) will make the interface size normal, but font rendering may become blurry. There're some workaround for it in upstream issues, but not perfect.

**Comment by tsl0922** [comment]
Should be fixed on latest main branch now, try the dev build: https://github.com/tsl0922/ImPlay/releases/tag/continuous

<img width="798" alt="image" src="https://user-images.githubusercontent.com/1680515/218358579-59c9ae6d-ccff-44c8-aa0c-79ed87576014.png">
