### ISSUE TITLE
--fs argument from command line not working properly on Windows

### ISSUE THREAD

**Issue by SilentNightx** [tsl0922/ImPlay#30]
When running ImPlay.exe with mpv arguments from PowerShell, using the --fs argument to playback video in full screen results in the video not expanding to the full screen size. Exiting and coming back to full screen manually allows the video to expand to the full resolution of the monitor. This behavior isn't present on the latest build of mpv and it works as it intended there.

To reproduce:
1. Open PowerShell.
2. `cd "C:\Program Files\ImPlay"`
3. `.\ImPlay.exe av://dshow:video="Integrated Camera" --fs`

Windows 11 22621

**Comment by tsl0922** [comment]
Can not reproduce with regular video file on windows 10, not sure if it is related to the protocol you use

**Comment by tsl0922** [comment]
Try the latest build: https://github.com/tsl0922/ImPlay/releases/tag/continuous
