### ISSUE TITLE
Unclickable osc

### ISSUE THREAD

**Issue by hooke007** [tsl0922/ImPlay#31]
**Describe the bug**
OSC is not clickable.

**To Reproduce**
Load a video and try to click any button on OSC.

**Expected behavior**
Any button should work as user's expectations.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [e.g. Mac OS]
 - Version [e.g. 13.2]

**Additional context**
N/A

**Comment by tsl0922** [comment]
Reproduced on macOS, should be related to the high DPI related fix.

**Comment by tsl0922** [comment]
fixed on latest main branch.
