### ISSUE TITLE
add bookmark and open next or previous file in the currently playing files directory.

### ISSUE THREAD

**Issue by candrapersada** [tsl0922/ImPlay#33]
Feature request add bookmark and open next or previous file in the currently playing files directory. and tracks
![gambar](https://user-images.githubusercontent.com/36833664/219297684-1f5a82f5-933c-4b0a-b8a1-64d255e71641.png)
from ImPlay
![gambar](https://user-images.githubusercontent.com/36833664/219297879-f693540b-0fa7-4b61-aefb-138d217ff73f.png)

**Comment by tsl0922** [comment]
I prefer to implement features that requires gui operation in ImPlay.

This seems to be related to playlist manipulation only. It should be possible to implement it with lua script, have you searched it?

**Comment by candrapersada** [comment]
but I want it to be available by default without manually installing like mpvnet

**Comment by tsl0922** [comment]
You may want to use `autoload.lua` from mpv official repo:

https://github.com/mpv-player/mpv/tree/master/TOOLS/lua
