### ISSUE TITLE
Adds support of russian streaming websites "ok.ru" and "rutube.ru"

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#34]
Hello, thank you again fr this awesme player ! Please i have request : i wish to play this video from ok.ru with ImPlay  but i can't, it is impossible to play this video despite yt-dlp has support of ok.ru videos platform :(

https://ok.ru/video/529769433747

Also, it will be great if there if we can  play videos from famous rutube.ru ! Thank you !

**Comment by tsl0922** [comment]
If yt-dlp supports it, then it should work on ImPlay.

BTW, I can play the link you provide with ImPlay.

**Comment by trimechee** [comment]
@tsl0922  When I put the link of the video in ImPlayer, a different video from the video I chose appeared (ads?) and the video lasts 3 seconds then freezes, maybe because I didn't updated ImPlayer for a few days or because my internet connection is not powerful enough and ImPlayer has chosen the highest resolution video quality so the video has frozen...
 or maybe there is a missing codec in my computer, maybe i need lav filters codecs ? so ImPlayer is compatible with Lav filters?

I think I will try to install "3DYD Youtube Source" which is a set of plugins for watching videos from media sites directly in the video player...

https://ys.3dyd.com/

Please can you make ImPlayer compatible with 3DYD Youtube Source?

**Comment by trimechee** [comment]
I see you close the issue, ImPlayer doesn't have log files so i can send you the logs so you can you analyze and find the bug that prevents me from rplayback the videos of ok.ru please?

**Comment by tsl0922** [comment]
It has nothing with ImPlay, the video is selected by yt-dlp, you should tune yt-dlp's options.

- https://mpv.io/manual/stable/#options-ytdl-format
- https://mpv.io/manual/stable/#options-ytdl-raw-options

> ImPlayer doesn't have log files

You can view logs in `Tools - Metrisc & Debug` (make sure you have selected a log level first).

**Comment by trimechee** [comment]
Great ! Thank you so much for your precious help :)  In sha Allah i will try to install the last version of ImPlay and try different videos and see what happens...

**Comment by trimechee** [comment]
I install the last version of ImPlayer choose another video from ok.ru and it works ! but it lags, probably because my connection is not strong and ImPlayer chooses the highest video quality :( fortunately I can pause the video and I see the media buffer cache increase so I can play the video somehow, I hope the full buffer streaming media until the end will not be removed from our beloevd ImPlayer because it is a very useful feature for people with weak connection: (hope that ImPlayer will add option which allows to play standard quality videos by default :)
