### ISSUE TITLE
ImPlay does not read from standard input when given as "-"

### ISSUE THREAD

**Issue by KaMyKaSii** [tsl0922/ImPlay#35]
**Describe the bug**
I just discovered the player and would like to use it as the player for the streamlink instead of the default mpv, but the player opens without playing any media. After doing some tests, I noticed that "cat somemediafile | ImPlay -" does not work where in the default mpv it works perfectly. Replacing "-" with "/dev/stdin" makes ImPlay able to play the content.

**Expected behavior**
I expect "-" to work normally as well as "/dev/stdin" to maintain compatibility with other programs.

**Environment (please complete the following information):**
 - OS: Linux Mint
 - Version 21.1

**Comment by tsl0922** [comment]
added support on the latest main branch.

you can try it with the dev build: https://github.com/tsl0922/ImPlay/releases/tag/continuous
