### ISSUE TITLE
Keyboard shortcut to play automatically streaming link from clipboard 

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#36]
Hello, I often copy and paste streaming links and I find that using a keyboard shortcut allows us to open and play the links more faster, it will be great to add a shortcut "paste and play link from the clipboard" for example ctrl+v to play automatically the url adress of streaming links , to clarifiy I'm not just talking about paste links but about paste and alos playback and play automatically the links when using a keyboard shortcut ! Thank you very much !!

**Comment by tsl0922** [comment]
add `Ctrl+v script-message-to implay open-clipboard` to `input.conf` (you can find it via `Tools - Open Config Dir`).

**Comment by trimechee** [comment]
Great ! Thank you so much ! 🥇

**Comment by trimechee** [comment]
Hello @tsl0922 , thank you fr the new version ! 💯 

Please i have serious problem of playback : I made a space from the last paragraph in input.conf and added:



Ctrl+v script-message-to implay open-clipboard



and I saved the file, then I open youtube and I copy the line from a youtube video then I open ImPlay and I click on ctrl + v and nothing happens, I click on the interface and on the "open clipboard" option and there is a black screen in ImPlay and I hear the audio stuttering and Implay hangs and I try to send the log but Implay shrinks to the task bar and hangs and I I hear a stuttering audio....I'm going to have to use the task manager or restart the computer to close Implay which is buggy :( we hope for a solution for this problem, thank you!
