### ISSUE TITLE
No Player resize (Static player size)

### ISSUE THREAD

**Issue by Soromeister** [tsl0922/ImPlay#37]
**Is your feature request related to a problem? Please describe.**
I open different video files of different resolutions. Concrete example: 1 video at 1080p and 1 video at 2160p
When opening the 1080p file, the window opens up in 1080p. If I open up the video at 2160p, the player window is much larger, occupying the entire screen. Player window should retain the 1080p size when opening 2160p video files (also for smaller sizes).

**Describe the solution you'd like**
Opening videos will always maintain the set values for the window, like for example setting the window size to 1920x1080 will open any video with the window size of 1920x1080p, regardless if the video is larger or smaller.

**Describe alternatives you've considered**
Other video players like MPV-Net has this. Also PotPlayer or KMPlayer.

**Additional context**
If this is possible to do, it is not clear in the documentation and information should be made available on how to implement it.

**Comment by tsl0922** [comment]
Does the mpv [--autofit](https://mpv.io/manual/stable/#options-autofit) and it's related options meet your needs? I'm going to implement them in #27

**Comment by Soromeister** [comment]
Any progress on this? Both --autofit and --auto-window-resize are ignored so far.

**Comment by tsl0922** [comment]
`--auto-window-resize` is supported now.

To make player window size static, add `auto-window-resize=no` to `mpv.conf`.
