### ISSUE TITLE
Single instance mode

### ISSUE THREAD

**Issue by Soromeister** [tsl0922/ImPlay#38]
**Is your feature request related to a problem? Please describe.**
When I already have a video open, if I open another video, the new video opens up a new ImPlay window, so I get 2 videos playing at the same time.

**Describe the solution you'd like**
Opening other videos while already having a video open should open in same player window.

**Describe alternatives you've considered**
Other players like MPV-Net or PotPlayer or KMPlayer offer this option.

**Comment by tsl0922** [comment]
It may be useful, but mpv does not support it natively: https://github.com/mpv-player/mpv/issues/3811

**Comment by Soromeister** [comment]
Does [ImGui](https://github.com/ocornut/imgui) support fine-grained control over launching `mpv`?

If so, is it possible to add function to close previous `mpv` instance and open a new one in the same `ImGui` window?

**Comment by tsl0922** [comment]
It has nothing to do with ImGui.

There's already scripts that can do this in that mpv issue, I may add this feature when a portable way is found.

**Comment by tsl0922** [comment]
It's now supported via `Help - Settings - General - Single instance mode` in the latest main branch.

You can try it from: https://github.com/tsl0922/ImPlay/releases/tag/continuous

**Comment by candrapersada** [comment]
Opening new files will replace media playing in the existing window with a new playlist
