### ISSUE TITLE
反馈一下：远程桌面全屏时画面扭曲

### ISSUE THREAD

**Issue by twedu** [tsl0922/ImPlay#4]
连到nas上，播放nas里的剧集时点全屏就会都倾斜，而且没法退出
https://z4a.net/images/2023/01/07/Snipaste_2023-01-07_09-10-35.png
https://z4a.net/images/2023/01/07/Snipaste_2023-01-07_09-09-26.png

**Comment by twedu** [comment]
那台nas是没有连显示器的，出现上面的情况只好断开链接重新连接远程桌面才能正常。

**Comment by tsl0922** [comment]
可能和驱动什么的有关系（OpenGL 支持问题），不是程序上能解决的。
