### ISSUE TITLE
Use external langauge file for GUI

### ISSUE THREAD

**Issue by bovirus** [tsl0922/ImPlay#41]
**Is your feature request related to a problem? Please describe.**

Modify source code to use external text language file (editable).

In this way translator can create/modify/test translation without waiting an app rebuild.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bovirus** [comment]
@tsl0922 

Thanks.
very good news.

**Comment by tsl0922** [comment]
It's supported on the latest main branch now, you can test it via the dev build:

https://github.com/tsl0922/ImPlay/releases/tag/continuous

**Comment by bovirus** [comment]
@tsl0922 

Thanks.
It seems OK.
Where are located (path) the translation files?

**Comment by tsl0922** [comment]
> @tsl0922 
> 
> 
> 
> Thanks.
> 
> It seems OK.
> 
> Where are located (path) the translation files?
> 
> 

Put the lang json file under the `<config dir>/lang` folder.

`<config dir>` can be opened via `Tools - Open Config Dir`.

**Comment by bovirus** [comment]
@tsl0922 

I explained better.

In ImPlay I found the GUI already translated but in ImPlay fodler/sunfodler I didn't find json external file.
Where are the external langauge files of current translation of IMPlay?

**Comment by tsl0922** [comment]
It's still compiled into the binary. 

But if you put an external translation file into <config dir>/lang, it will be loaded first.

**Comment by bovirus** [comment]
@tsl0922 

Proposal of changes

Add in github home page info how to add a new language with external language file
Add in readme of the program info how to add new language with an external language file
Create in program archive distribution "lang" subfolder
Levae only english language embedded in exe file.
Move not english language (italian/chinese) from embeedded to exetenl json file in "lang" subfolder.

**Comment by tsl0922** [comment]
nope, I don't think most of users will need this feature, embed language files to the executable is better.

**Comment by bovirus** [comment]
@tsl0922 

At least add "lang" subfodler to archive distribution.
