### ISSUE TITLE
Settings - Move Settings menu from Help submenu to main window

### ISSUE THREAD

**Issue by bovirus** [tsl0922/ImPlay#42]
**Is your feature request related to a problem? Please describe.**

I believe that is more common and useful to have "Settings" menu in main menu instead like now under "Hep" menu.

**Describe the solution you'd like**

Move "Settings" menu from "Help" submenu to main menu.

**Describe alternatives you've considered**

**Additional context**

**Comment by tsl0922** [comment]
Done.

Try the latest build: https://github.com/tsl0922/ImPlay/releases/tag/continuous
