### ISSUE TITLE
Playlist supports custom sorting

### ISSUE THREAD

**Issue by dijingkai** [tsl0922/ImPlay#43]
**Is your feature request related to a problem? Please describe.**
+ Garbled characters appear when the file name in the playlist is Chinese
+ The playlist does not support sorting. 

**Describe the solution you'd like**
+ Fix the Chinese garbled problem
+ Can the playlist be sorted by file name, file size, and duration etc. like PotPlayer?

**Describe alternatives you've considered**

**Additional context**
+ Chinese garbled problem
<img width="961" alt="1678179968745" src="https://user-images.githubusercontent.com/122948706/223375157-e7afe36d-da02-43dd-95c8-c6a8256156c6.png">

+ Sorting function of potplayer
<img width="273" alt="image" src="https://user-images.githubusercontent.com/122948706/223375551-530fe74f-b18e-4533-8abe-e9cf01107ce8.png">

**Comment by tsl0922** [comment]
> Garbled characters appear when the file name in the playlist is Chinese

Select Glyph Ranges in `Help-Settings-Font`

**Comment by tsl0922** [comment]
Need a natural sort algorithm like: https://github.com/mpv-player/mpv/pull/6027

**Comment by dijingkai** [comment]
> Need a natural sort algorithm like: [mpv-player/mpv#6027](https://github.com/mpv-player/mpv/pull/6027)

I read the issue and said that the code has been merged, but I didn't find any code in the master branch. Instead, I found a lua script [autoload.lua](https://github.com/mpv-player/mpv/blob/855b619cc9872a2919d071166d5b50d6a2a8a708/TOOLS/lua/autoload.lua#L100) and used it first.
