### ISSUE TITLE
Changing font doesn't work

### ISSUE THREAD

**Issue by RibShark** [tsl0922/ImPlay#48]
**Describe the bug**
I am trying to change the font through the settings dialog or implay.conf, but the font does not change.

**To Reproduce**
1. Go to the settings dialog.
2. Click on the font tab.
3. Click the open folder button.
4. Select a ttf file.
5. Restart ImPlay.

**Expected behavior**
The interface font should be changed to the selected ttf.

**Actual behavior**
The interface font still appears to be the default monospace font.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Version: 22H2

**Comment by tsl0922** [comment]
Fixed on the latest main branch.

You can test it via: https://github.com/tsl0922/ImPlay/releases/tag/continuous
