### ISSUE TITLE
[Feature request]: Support regular glfw3

### ISSUE THREAD

**Issue by lgbaldoni** [tsl0922/ImPlay#5]
Hello,
I packaged ImPlay for openSUSE Linux and out of security concerns it's generally considered good practice to rely on distro-supplied shared libraries.
Now fmt, json and nfd are straight replacements, but the glfw3 supplied by ImPlay is [patched](https://github.com/glfw/glfw/tree/drag-window): is there a way to separate those additional functions from the library so that the app could use the regular library?

**Comment by tsl0922** [comment]
OK, I will provide a CMake option for it.

**Comment by tsl0922** [comment]
You can now use `-DUSE_PATCHED_GLFW=OFF` to disable the use of patched glfw, but it will make window dragging to be unsupported.
