### ISSUE TITLE
mouse_leave keybind

### ISSUE THREAD

**Issue by po5** [tsl0922/ImPlay#51]
**Is your feature request related to a problem? Please describe.**
Lua scripts such as osc.lua use it.
Hover on the vanilla osc's timeline at the bottom, then off the window. The timeline should hide.

**Describe the solution you'd like**
mouse_leave and other related keybinds are fired.

**Describe alternatives you've considered**
No alternatives.

**Comment by tsl0922** [comment]
Maybe related to #61, It should work on the latest build.
