### ISSUE TITLE
Moon to choose video quality choice

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#53]
Hello, ImPlay is amazing, the only thing missing is a quick option in the GUI to choose the youtube video quality for example, moonpalyer made by coslyk is also based on mpv and yt-dlp and displays a window when copying and pasting a url address of video streaming so that we can choose the desired video quality, we hope that our beloved ImPlayer will do the same thing soon! 

we hope also that ImPlay has integrated automatic updater of yt-dlp, because ImPlay doesn't use the last version of yt-dlp, ImPlay use yt-dlp of 17/02/2023...

https://github.com/coslyk/moonplayer

https://coslyk.github.io/moonplayer.html

**Comment by tsl0922** [comment]
#68
