### ISSUE TITLE
Bugged resize cursor 

### ISSUE THREAD

**Issue by BODZy** [tsl0922/ImPlay#55]
With no-border/border=no resize, cursor starts flickering when trying to resize the window

**Environment:**
 - OS: [Windows 10]
 - Version [22H2]

**Comment by BlueIncog** [comment]
Boost
This bug is quite jarring to look at, + it makes resizing 10x harder

https://github.com/tsl0922/ImPlay/assets/53572359/b42ada50-66c8-4ea8-a515-9f2c3f3d2122

**Comment by tsl0922** [comment]
It's a known issue to me, maybe we need a patch for imgui.

**Comment by tsl0922** [comment]
Fixed by 74a795d6ce5eb86996be904c336a7459ac867a2e

you may want to try the latest dev build: https://github.com/tsl0922/ImPlay/releases/tag/continuous
