### ISSUE TITLE
Player window stutters when moved

### ISSUE THREAD

**Issue by FranTesla** [tsl0922/ImPlay#56]
When the main window is moved around on the desktop, the "framerate" of the window itself seems lower that any other program, even without being playing anything at all (no open files), other mpv players don't do that, and I don't remember other windows program doing this either (maybe some OpenGL ones that update rarely)

**To Reproduce**
just run the player and click grab the window and move it around 

**Expected behavior**
smooth window moving like any other program

**Environment (please complete the following information):**
Windows 11 (21H2)

**Additional context**
I'm guessing is related to the ability to move the window by clicking anywhere, but other MPV players don't have this issue

**Comment by tsl0922** [comment]
Try the latest build: https://github.com/tsl0922/ImPlay/releases/tag/continuous
