### ISSUE TITLE
Add support to VapourSynth Playback and .vpy scripts inside mpv.conf

### ISSUE THREAD

**Issue by ThomasEricB** [tsl0922/ImPlay#57]
This is the only reason keeping me from swapping from mpv.net. Right now, it is the only mpv based GUI player with VapourSynth support. Please consider adding it. See:

https://github.com/mpvnet-player/mpv.net/blob/master/docs/Manual.md#advanced-features

https://github.com/stax76/mpv.net/wiki/Using-VapourSynth-in-mpv.net

**Comment by tsl0922** [comment]
Have you tried it? It should work.

I've tested it on windows ,it works fine.

**Comment by tsl0922** [comment]
Added a wiki page: https://github.com/tsl0922/ImPlay/wiki/VapourSynth
