### ISSUE TITLE
window-maximized doesn't work when pressing the next video

### ISSUE THREAD

**Issue by candrapersada** [tsl0922/ImPlay#59]
**Describe the bug**
when playing the next video, window-maximized doesn't work and the monitor size becomes smaller

**To Reproduce**
1. Go to 'File Explorer'
2. Click on 'open video with implay'

**Expected behavior**
Is there a way to make the monitor size not change when pressing the next video button?

**Environment (please complete the following information):**
 Windows 10
 22H2

**Comment by tsl0922** [comment]
Fixed, you may want to try the latest build: https://github.com/tsl0922/ImPlay/releases/tag/continuous
