### ISSUE TITLE
2 presets preconfigured options: worst video and best video

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#60]
Edit :
today I installed the latest version of Smplayer and .... I can finally play the videos of ok.ru and rutube and sibnet by choosing the quality I prefer (stadard quality 480p) !!!

we hope one day our beloved ImPlay will be able also to let us to choose the video quality from the GUI  just like smplayer specially because smplayer is based on mpv player and yt-dlp.... 

Hello, we know some videos has many different video quality and many audio dash streams like in youtube, and so my suggestion is to add only 2 presets preconfigured options : worst video and best video, : and even worst audio which is an option to select audio only stream when available and best audio, so the user who has a strong connection will use the bestvideo preset by default, and the user who has a bad internet connection will choose and always use the worst video option by default, it's useful for example for the site: https://my.mail.ru/video containing a lot of streaming videos, there are only 2 video qualities: 360p and 1080p and watching with the yt-dlp worst video option i.e. 360p is acceptable and excellent, the video quality is excellent even in 360p, thank you very much! i tried to add lua script and add raw-options to yt-dlp etc but i didn't understand how to do it hence my suggestion....thanks!

**Comment by tsl0922** [comment]
#68
