### ISSUE TITLE
Add mouse-pos property

### ISSUE THREAD

**Issue by po5** [tsl0922/ImPlay#61]
**Is your feature request related to a problem? Please describe.**
[uosc](https://github.com/tomasklaen/uosc) displays nothing with ImPlay since uosc version [4.3.0](https://github.com/tomasklaen/uosc/releases/tag/4.3.0).

**Describe the solution you'd like**
Implement the `mouse-pos` property (with `x`, `y`, `hover` sub-properties), which uosc relies on since 4.3.0.

**Describe alternatives you've considered**
Using old versions of uosc, which are missing bug fixes and new features.

**Additional context**
I am using ImPlay CI AppImage build for fec61341f30688f3b62e53e868555d8fcdb3994a.

**Comment by tsl0922** [comment]
Can't reproduce on windows.

[mouse-pos](https://mpv.io/manual/master/#command-interface-mouse-pos) propertity is not writable, it's generated by mpv itself from mouse events.

**Comment by po5** [comment]
What part can you not reproduce? `mouse-pos` is not broadcast with ImPlay, when it works with other frontends like mpv.net.

**Comment by tsl0922** [comment]
The `mouse-pos` was added in mpv [v0.33.0](https://github.com/mpv-player/mpv/releases/tag/v0.33.0), while the mpv version in appimage is `0.32.0`.

**Comment by tsl0922** [comment]
Try the latest dev build: https://github.com/tsl0922/ImPlay/releases/tag/continuous
