### ISSUE TITLE
cannot play online video stream to use youtube URL 

### ISSUE THREAD

**Issue by newyorkthink** [tsl0922/ImPlay#62]
![image](https://github.com/tsl0922/ImPlay/assets/87791643/d4ec2e11-f2d2-41b3-9521-264cb93668b6)

it just show still black ,cannot operate anything

**Comment by BlueIncog** [comment]
I had the same problem, a temporary solution would be to use this MPV config:
https://github.com/NaiveInvestigator/mpv-config (just adjust the mpv.conf and only keep these scripts:
![image](https://github.com/tsl0922/ImPlay/assets/53572359/24f3d706-7b0a-4d1b-b93e-6c81bd39999e)
also include the fonts folder

**Comment by tsl0922** [comment]
yt-dlp is not included in the `.AppImage` package, you may want to install it yourself.
