### ISSUE TITLE
Quickmenu ImGUI window

### ISSUE THREAD

**Issue by BlueIncog** [tsl0922/ImPlay#64]
I would like to move around tabs in the quickmenu, like you can with the debug window
![image](https://github.com/tsl0922/ImPlay/assets/53572359/cf00f5a7-2fb9-4b6e-9e43-7566bea02ad8)

![image](https://github.com/tsl0922/ImPlay/assets/53572359/d18a0985-d3fe-4b48-8c85-9dd9d62f5773)

It makes watching long video's with lots of chapters a lot easier, however the current quickmenu is taking up a lot of the screen and I cant resize it, therefore I am asking to enable a resize/ move option for the quickmenu

**Comment by tsl0922** [comment]
9d6d1f58754032e3ea5a313ff8534b8439dc13f7
