### ISSUE TITLE
Unable to set it up

### ISSUE THREAD

**Issue by bheeshmpita** [tsl0922/ImPlay#65]
I have read the FAQ and done config with hit and trial but unable to set it up.
I want to use mpv config (with some changes) and use the context menu of implay. for eg. in my mpv settings i have configured it such that the video does play in a window size of defined geometry but while playing the video this program it resets to original window size. I think it is to do with the scale setting of the program. How can i implement that restricted window size such as it does not go beyond 1280x720 irrespective of the video resolution.

My second query is video streaming. i stream YT videos with mpv and chrome extension playwithmpv. How can i configure it to work with implay?

**Comment by tsl0922** [comment]
see #27, not all window related mpv options are supported yet.

**Comment by tsl0922** [comment]
To make player window size static, add `auto-window-resize=no` to mpv.conf (#37)

**Comment by tsl0922** [comment]
Closing as your requests are tracked in #27 already.
