### ISSUE TITLE
Uosc for video quality 

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#68]
Hello, a developer was kind enough to inform me of the existence of the wonderful Uosc, it will be great to make ImPlay even more easy and simple to use for beginners and crowds to add this program natively and it will allow beginners to choose easily the desired streaming video quality, thank you very much!

Feature-rich minimalist proximity-based UI for MPV player:

https://github.com/tomasklaen/uosc

https://github.com/natural-harmonia-gropius/mpv-config

https://github.com/christoph-heinrich/mpv-quality-menu

**Comment by tsl0922** [comment]
It's supported on the latest [build](https://github.com/tsl0922/ImPlay/releases/tag/continuous) now.

**Comment by trimechee** [comment]
Absolutely awesome amazing ! Thank you so much Mr @tsl0922 :) 💯 🥇
