### ISSUE TITLE
Pure Black  for white top bar

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#71]
Hello, dark mode allows us to reduce blue light which can tire our eyes at night, save battery power...I like the pure full black mode theme which looks like the high contrast theme, so we would like please for more visual comfort a pure black theme color even in the white top bar, thank you !

**Comment by tsl0922** [comment]
Duplicate of #10

**Comment by trimechee** [comment]
Hello @tsl0922 , th
