### ISSUE TITLE
Impossible to play videos from https://my.mail.ru/video 

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#72]
Hello, " my.mail.ru/video " is supported by y-dlp bu sadly, ImPlay can't play videos from this famous russian website : 

https://my.mail.ru/v/hotpsychologies_tv/video/3/530.html

**Comment by tsl0922** [comment]
https://github.com/tsl0922/ImPlay/issues/34#issuecomment-1435694728

**Comment by trimechee** [comment]
Hello Mr @tsl0922 , thank you :)

 Excuse me again but i don't think it's duplicate issue  because i can play videos from "ok.ru"  and "rutube.ru" but the new thing we can't play video from this very famous streaming site "my.mail.ru/video".....i tried with many media player that use yt-dlp but fails even that yt-dlp support downloading video from "my.mail.ru/video", for example with this great  downloader that use yt-dlp, we can donwload videos from my.mail.ru/video ! 


https://github.com/mhogomchungu/media-downloader


but the problem is that we can't play videos when using media players like ImPlayer, mpc be, mpc hc, mpc qt.....


So I have asked the developer of QMPlay2 that uses yt-dlp to fix this problem and the developer of QMPLAY2 media player has succeeded to resolve this problem of playback video from my.mail.ru/video , so the problem is in the different media players or in this web site which apparently blocks the media players like ImPlay and the problem is not in yt-dlp which can download the videos from this site since QMPLAY2 has succeeded to playback video from my.mail.ru/video ....

https://github.com/zaps166/QMPlay2/releases

Thank you :)
