### ISSUE TITLE
Bypass Youtube throttling

### ISSUE THREAD

**Issue by GunGunGun** [tsl0922/ImPlay#74]
**Is your feature request related to a problem? Please describe.**
You slows down download speed of non-720, as mentioned:
https://github.com/mpv-player/mpv/issues/11402#issuecomment-1456053016

**Describe the solution you'd like**
By split download into =<10MB chunks you bypass Youtube's rate limit.

**Describe alternatives you've considered**
We could write our own middleware proxy to split download into chunks, instead of relying on mpv and ffmpeg.

**Additional context**
No, but this is nice to have because it's quite annoying to not being able to watch Youtube at full speed, and more the rate limit can be brutal, because they usually limit download speed to 700-800KB/s, which is slow enough to make Youtube near unwatchable.

**Comment by tsl0922** [comment]
It has nothing to do with this player, the yt-dl support is provided by mpv.
