### ISSUE TITLE
ImPlay Fails To Startup

### ISSUE THREAD

**Issue by Karma2424** [tsl0922/ImPlay#77]
**Describe the bug**
ImPlay fails to create a create gui window

**To Reproduce**
Download the release 1.5.1
Try to launch ImPlay

**Expected behavior**
ImPlay should startup without any problems

**Screenshots**
![WindowsTerminal_daKuE9quoy](https://github.com/tsl0922/ImPlay/assets/58363516/5b4f5ca7-9721-4e57-a7cb-09c9ebb4350d)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2 
 - OS Build: 19045.3930

**Additional context**
`GLFW [65543]: EGL: Failed to create context: Arguments are inconsistent`
`Error: Failed to create window!`

**Comment by Karma2424** [comment]
Also when build from source on windows the error changes to
`GLFW [65542]: WGL: The driver does not appear to support OpenGL`
`Error: Failed to create window!`

**Comment by tsl0922** [comment]
Maybe driver issue, your graphics driver does not support OpenGL.

**Comment by Karma2424** [comment]
is there anyway to use DirectX instead of OpenGL?

**Comment by tsl0922** [comment]
No, it's not supported by libmpv.

What's your graphics card?

**Comment by Karma2424** [comment]
> No, it's not supported by libmpv.

Then why does mpv runs no problem
> What's your graphics card?

Its Intel 1st Generation Intel HD Graphics

**Comment by tsl0922** [comment]
> Then why does mpv runs no problem?

Because mpv supportes it.

but mpv does not expose other render backend to libmpv (https://github.com/mpv-player/mpv/issues/5979), this project uses libmpv.

**Comment by Karma2424** [comment]
so there is no way to get this work without going into this rabbit hole?

**Comment by tsl0922** [comment]
Well, your graphics card is too old, I have no plan to support it, nor do I can test it.
