### ISSUE TITLE
window10下鼠标不隐藏

### ISSUE THREAD

**Issue by molezz** [tsl0922/ImPlay#8]
**Describe the bug**
window10下鼠标不隐藏

**To Reproduce**
windows10 工作站新版
同样环境mpv还是正常2秒后隐藏

**Expected behavior**
like mpv

**Screenshots**
none

**Environment (please complete the following information):**
win10 22H2 workstation
 

**Additional context**
none

**Comment by tsl0922** [comment]
Try the [latest build](https://github.com/tsl0922/ImPlay/releases/tag/continuous), should be fixed by 039b24b7f4be31f51e85868cfd40c712487ca7f4.
