### ISSUE TITLE
MediaPlayPause not working on Windows

### ISSUE THREAD

**Issue by CmcnPro** [tsl0922/ImPlay#82]
**Describe the bug**
When I click MediaPlayPause, it's now working.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Version 23H2 22631.3374
 - Implay Version 1.5.1-c4e38ed1

**Comment by tsl0922** [comment]
Use the latest [dev](https://github.com/tsl0922/ImPlay/releases/tag/continuous) version, and add `media-controls=yes` to `mpv.conf`.

Ref: https://github.com/mpv-player/mpv/pull/14338
