### ISSUE TITLE
SPDIF Audio Setting 

### ISSUE THREAD

**Issue by brusezot** [tsl0922/ImPlay#83]
Hi Thank a lot for your job, do you think is possible to include a feature inside audio settings about audio passthrouth (SPDIF) value : 

audio-spdif=ac3,eac3,dts-hd,truehd 
audio-channels=7.1,5.1,stereo 

Thanks ;)

**Comment by tsl0922** [comment]
Do you mean a GUI option? 

No, but you can add it to `mpv.conf` yourself.
