### ISSUE TITLE
Please make 32 bits version for Windows 7 OS

### ISSUE THREAD

**Issue by trimechee** [tsl0922/ImPlay#85]
Hello, Our beloved ImPlay is the most powerful media player in the world, thank you so much for this awesome amazing media player! 💯 🥇

Recently my laptop broke down and I went back to using my old laptop made in 2012 which has windows 7 os 32 bits, I was hoping to use our beloved  ImPlay because streaming videos freeze lag on the heavy web browser but apparently there is no 32-bit version for windows 7 of  ImPlay and we hope please there will be a version of  ImPlay for windws 7 os 32 bts, please, because surely, millions of people still have machines with the legendary windows 7 os and the old machines are robust and still work and the  ImPlay is useful to save these machines from destruction, thank you very much !

**Comment by trimechee** [comment]
@Andarwinux this is not shit, millions of users and machines still use windows 7 os and these machines are robust efficient,my laptop windows 7 has has no fan so I enjoy the silence and no dust like in modern machines, i read the interview of famous develper who said computers and machine from the 90s are better and faster than modern machines because nowadays, machines and softwares and developers tend to overcomplicate things

**Comment by z3ch5** [comment]
Hey @trimechee  take it easy man,
I may suggest you learn Linux and install it on your laptop ;)
You won't go back, even very old machines can handle an 64 bits Linux

**Comment by trimechee** [comment]
Hi @z3ch5 , thank you for your kinsnesse and yout precious advice ! 

yes light distro linux  is a good option option, yes but my concern is hardware compatibility with my old laptop, I have a windows original  7 os without crack , and I found a lot of web browser and media player compatible with my windows 7 32 bits like supermium, thorium legacy, catsxp, yandex, r3dfox, luminafox, potplayer, qmplay2, vlc, mpc be, mpc hc, firefox esr, kmplayer, pale moon, basilisk !

in addition I discover that the Open in vlc extension for firefox works with my favorite streaming site so fr the moment windows 7 os pleases me enough :)

**Comment by tsl0922** [comment]
No.

Ref: https://github.com/mpv-player/mpv/commit/ab3d0b73f799bfaaa018a3350a246a11c6a52feb
