### ISSUE TITLE
Native media player integration in Windows

### ISSUE THREAD

**Issue by rollingmoai** [tsl0922/ImPlay#9]
**Is your feature request related to a problem? Please describe.**

ImPlay needs native media player integration in Windows.

**Describe the solution you'd like**

Here is a checklist:
- [ ] Taskbar progress bar (Native in MPV)
- [ ] SMTC (https://github.com/datasone/MPVMediaControl)
- [ ] Taskbar buttons (https://github.com/qwerty12/mpv-taskbar-buttons)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by tsl0922** [comment]
I'm not a fan of this feature.

If anyone want to implement it, I'm happy to merge the PR.

**Comment by tsl0922** [comment]
added support for taskbar progress, the others are not planned.
